# This is a basic workflow to help you get started with Actions

name: GET and POST tests 

on:
  schedule:
   - cron: "00 00 * * 1-5"

jobs:
  API_GET:
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Runs a single command using the runners shell
      - name: Prepare reports folder
        run: mkdir Reports
        
      - name: install setup-tools
        run: sudo pip3 install setuptools

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo pip3 install \
            robotframework==4.0.3 \
            robotframework-requests==0.9.3 \

      - name: Run tests
        run: |
          robot -i api -i get -x results -T -d Reports/.

      - name: Archive test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: Reports/*
